---
abstract: 'Data domain classes for IP addresses'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Domain-Net
provides:
  Data::Domain::Net:
    file: lib/Data/Domain/Net.pm
    version: 1.100840
  Data::Domain::Net::IPAddress:
    file: lib/Data/Domain/Net/IPAddress.pm
    version: 1.100840
  Data::Domain::Net::IPAddress::IPv4:
    file: lib/Data/Domain/Net/IPAddress/IPv4.pm
    version: 1.100840
  Data::Domain::Net::IPAddress::IPv4_TEST:
    file: lib/Data/Domain/Net/IPAddress/IPv4_TEST.pm
    version: 1.100840
  Data::Domain::Net::IPAddress::IPv6:
    file: lib/Data/Domain/Net/IPAddress/IPv6.pm
    version: 1.100840
  Data::Domain::Net::IPAddress::IPv6_TEST:
    file: lib/Data/Domain/Net/IPAddress/IPv6_TEST.pm
    version: 1.100840
requires:
  Carp: 0
  Data::Domain::SemanticAdapter: 0
  Data::Domain::SemanticAdapter::Test: 0
  Data::Semantic::Net::IPAddress::TestData::IPv4: 0
  Data::Semantic::Net::IPAddress::TestData::IPv6: 0
  English: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::CompanionClasses: 0
  Test::More: 0.88
  constant: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Data-Domain-Net
  homepage: http://search.cpan.org/dist/Data-Domain-Net/
  repository: http://github.com/hanekomu/Data-Domain-Net
version: 1.100840
